### PR TITLE
Revert "Semi-automateed XBlock translation pull"

### PR DESCRIPTION
**Pull request by OmarIthawi**
Reverts openedx/openedx-i18n#4

I'm undoing all the work I've done here. It's not really that useful and we need a bot to do that work instead of keeping it in a repo.

As discussed in #6, I'm working with Ned on a better automated method.

Thanks @regisb for the help, time to clean this up.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3833](https://openedx.atlassian.net/browse/OSPR-3833) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by regisb** [comment]
So sad! Should I merge this as it is?

**Comment by OmarIthawi** [comment]
Thanks @regisb. Yes please.

It's not really that sad. We're looking for a better alternative that involves less human work and more robots.

**Comment by regisb** [comment]
:robot: :fist_raised:

**Pull request merged**
