### PR TITLE
Add simplified Chinese.

### PR DESCRIPTION
**Pull request by pcliupc**
Add translation for simplified Chinese.

The translations are downloaded from juniper.rc2.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pcliupc! I've created [OSPR-4513](https://openedx.atlassian.net/browse/OSPR-4513) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by regisb** [comment]
@pcliupc Unless I'm mistaken, simplified Chinese (zh_CN) translations are already present in the edx-platform repositor; see for instance this django.po file: https://github.com/edx/edx-platform/blob/master/conf/locale/zh_CN/LC_MESSAGES/django.po

This repo should only contain languages that are not already shipped with edx-platform. What exactly are you trying to achieve?

**Comment by natabene** [comment]
@pcliupc Thank you for your attempt to contribute. Please sign the agreement so we can review your code. As noted by @regisb, Simplified Chinese should already be included.

**Comment by pcliupc** [comment]
@regisb @natabene Got you, I misunderstood the use of this repo. Thanks.

**Pull request closed without merging**
